homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.home, name = "home"),
    path('logout', views.logout, name = "logout"),
    path('profile', views.profile, name = "profile"),
] 

page/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homepage.urls')),
    path('', include('register.urls')),
    path('admin/', admin.site.urls),
]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns = [
    path('signup/', views.signup, name = "signup"),
    path('login/', views.login, name = "login"),
]

homepage/models.py
from django.db import models

# Create your models here.

register/models.py
from django.db import models

class User(models.Model):

    mName = models.CharField(max_length = 20)
    mUsername = models.CharField(max_length = 20, primary_key=True)
    mEmail = models.CharField(max_length = 30)
    mPhone = models.CharField(max_length = 10)
    mPassword = models.CharField(max_length = 30)

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from register.models import User

def home(request):

    try:
        request.session['username']

        print("logged in")
        context = {
            'in':'none',
            'out':'block',
        }
        if request.method == 'GET':
            if ((request.GET.get('songText') is not None) and (request.GET.get('songText').strip() != '')):
                context['songname'] = request.GET.get('songText')
                context['visual'] = 'block'
            else:
                context['visual'] = 'none'

        return render(request, 'homepage/home.html',context)
    except:
        context = {
            'in':'block',
            'out':'none',
        }
        return render(request, 'homepage/home.html',context)
        
def logout(request):
    try:
        del request.session['username']
    finally:
        return redirect('/')

def profile(request):
    try:
        m = request.session['username']
        p = User.objects.get(mUsername = m)
        name = p.mName
        username = p.mUsername
        email = p.mEmail
        phone = p.mPhone
        context = {
            'name': name,
            'username': username,
            'email': email,
            'phone': phone,
            'value': 'readonly',
            'allow': True,
            'in': 'none',
            'out': 'block',
            'valname':'Change',
        }
        if 'Save' == request.POST.get('submit'):
            context['value'] = 'readonly'
            context['valname'] = 'Change'
            p = User.objects.get(mUsername = m)
            if request.POST.get('name').strip() != '':
                p.mName = request.POST.get('name')
                p.save()
                context['name'] = p.mName
            if request.POST.get('email').strip() != '':
                p.mEmail = request.POST.get('email')
                p.save()
                context['email'] = p.mEmail
            if request.POST.get('phone').strip() != '':
                p.mPhone = request.POST.get('phone')
                p.save()
                context['phone'] = p.mPhone

        elif request.POST.get('submit'):
            context['value'] = ''
            context['valname'] = 'Save'
        return render(request, 'homepage/home.html', context)
    except:
        return redirect('/')

register/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import User
from homepage.views import home

def signup(request):
    try:
        print(request.session['username'])
        return redirect('/')
    except:
        if(request.method == 'POST'):

            name = request.POST.get('name')
            username = request.POST.get('username')
            email = request.POST.get('email')
            phone = request.POST.get('phone')
            password = request.POST.get('password')

            #entering data into model....
            p = User.objects.create(mName = name, mUsername = username, mEmail = email, mPhone = phone, mPassword = password)
            p.save()
            return redirect('/login/')
        else:
            return render(request, 'register/signup.html')

def login(request):

    try:
        print(request.session['username'])
        return redirect('/')
    except:
        if(request.method == 'POST'):
            Username = request.POST.get('username')
            Pass = request.POST.get('pass')

            a = User.objects.get(mUsername = Username)
            if(a.mPassword == Pass):
                request.session['username'] = Username
                return redirect('/')
        else:
            return render(request, 'register/login.html')

homepage/templates/homepage/home.html
<html>
<head><title>Home</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/css/home.css'%}">
</head>
<body bgcolor="#bb98ff">
<!--Navbar Started-->
    <div id = 'nav'>
        <a href = "{% url 'homepage:home' %}">
        <div id = "logo">
            COMPANY
        </div></a>
        <div id = "func">
        <div id = "register" style = "display:{{ in }};">
            <a href = "{% url 'register:login' %}">
            <div id = "in">
                Log In
            </div></a>
             <a href = "{% url 'register:signup' %}">
             <div id = "up">
               Sign Up
             </div></a>
        </div>
        <div id = "inside" style = "display:{{ out }};">
            <a href = "{% url 'homepage:profile' %}">
            <div id = "profile">
                Profile
            </div></a>
             <a href = "{% url 'homepage:logout' %}">
             <div id = "out">
               Log Out
             </div></a>
        </div>
        </div>
    </div>
<!--navbar completed-->


{% if allow %}
    <div style = "position: relative; z-index: 0;">
        {% include 'homepage/profile.html' %}</div>
{% else %}
    <form id = "songSearch" action="{% url 'homepage:home' %}" method = "get" style = "margin-top:200; ;">
        <label for = "songText">Enter name of a song</label>
        <input type = "text" name = "songText">
        <input type = "submit" value = "search">
    </form>
    <iframe style = "margin-top:10; display: {{ visual }}; width:100%; height:75%;" class="ytplayer"
      src="https://www.youtube.com/embed?listType=search&list={{songname}}"
      frameborder="0"></iframe>

{% endif %}
</body>
</html>

homepage/templates/homepage/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<title>Contact V8</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'homepage/images/icons/favicon.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/vendor/daterangepicker/daterangepicker.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'homepage/css/main.css' %}">
</head>
<body>

	<div class="container-contact100">
		<div class="wrap-contact100">
			<form class="contact100-form validate-form" action = "{% url 'homepage:profile' %}" method = "POST">
				{% csrf_token %}
				<span class="contact100-form-title">
					Hola {{ username }}
				</span>
				Name:
				<div class="wrap-input100 validate-input" >
					<input class="input100" type="text" name="name" placeholder = "{{name}}" {{value}}>
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>
				Username:
				<div class="wrap-input100 validate-input">
					<input class="input100" type="text" name="username" placeholder = "{{username}}" readonly>
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>
				Email:
				<div class="wrap-input100 validate-input">
					<input class="input100" type="text" name="email" placeholder = "{{email}}" {{value}}>
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>
				Mobile Number:
				<div class="wrap-input100 validate-input">
					<input class="input100" type="text" name="phone" placeholder = "{{phone}}" {{value}}>
					<span class="focus-input100-1"></span>
					<span class="focus-input100-2"></span>
				</div>

				<div class="container-contact100-form-btn">
					<input type = "submit" class="contact100-form-btn" name = "submit" value = "{{ valname }}">

					</input>
				</div>

			</form>
		</div>
	</div>


</body>
</html>

register/templates/register/login.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<link rel="icon" type="image/png" href="{% static 'register/images/icons/favicon.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/css-hamburgers/hamburgers.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/css/main.css'%}">
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style = "background:#4a1e9e;">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static '/register/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method = "POST" action="{% url 'register:login' %}">
					{% csrf_token %}
					<span class="login100-form-title">
						Member Login
					</span>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-envelope" aria-hidden="true"></i>
						</span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="pass" placeholder="Password">
						<span class="focus-input100"></span>
						<span class="symbol-input100">
							<i class="fa fa-lock" aria-hidden="true"></i>
						</span>
					</div>
					
					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>

					<div class="text-center p-t-12">
						<span class="txt1">
							Forgot
						</span>
						<a class="txt2" href="#">
							Username / Password?
						</a>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'register:signup' %}">
							Create your Account
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	<script src="{% static 'register/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{% static 'register/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'register/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
	<script src="{% static 'register/vendor/select2/select2.min.js'%}"></script>
	<script src="{% static 'register/vendor/tilt/tilt.jquery.min.js'%}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="{%static 'register/js/main.js'%}"></script>

</body>
</html>

register/templates/register/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
	{% load static %}
	<link rel="icon" type="image/png" href="{% static 'register/images/icons/favicon.ico' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/css-hamburgers/hamburgers.min.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/css/util.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'register/css/main.css'%}">
	<title>Sign Up</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<div class="limiter">
		<div class="container-login100" style = "background:#4a1e9e;">
			<div class="wrap-login100">
				<div class="login100-pic js-tilt" data-tilt>
					<img src="{% static '/register/images/img-01.png' %}" alt="IMG">
				</div>

				<form class="login100-form validate-form" method = "POST" action="{% url 'register:signup' %}">
					{% csrf_token %}
					<span class="login100-form-title">
						Member SignUp
					</span>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="name" placeholder="Full Name" required>
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="username" placeholder="Username" required>
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Valid email is required: ex@abc.xyz">
						<input class="input100" type="text" name="email" placeholder="Email">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input">
						<input class="input100" type="text" name="phone" placeholder="Mobile No" required>
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 validate-input" data-validate = "Password is required">
						<input class="input100" type="password" name="rpassword" placeholder="Re-Enter Password">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Sign Up
						</button>
					</div>

					<div class="text-center p-t-136">
						<a class="txt2" href="{% url 'register:login' %}">
							Already a Member
							<i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
						</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	<script src="{% static 'register/vendor/jquery/jquery-3.2.1.min.js'%}"></script>
	<script src="{% static 'register/vendor/bootstrap/js/popper.js'%}"></script>
	<script src="{% static 'register/vendor/bootstrap/js/bootstrap.min.js'%}"></script>
	<script src="{% static 'register/vendor/select2/select2.min.js'%}"></script>
	<script src="{% static 'register/vendor/tilt/tilt.jquery.min.js'%}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>
	<script src="{%static 'register/js/main.js'%}"></script>

</body>
</html>